name = "nextauthv5-clouadflare"
pages_build_output_dir = ".vercel/output/static"
compatibility_date = "2024-11-29"

[env.production]
compatibility_flags = [ "nodejs_compat" ]

[env.production.vars]
AUTH_GITHUB_ID = ""
AUTH_GITHUB_SECRET = ""
AUTH_SECRET = ""
GOOGLE_CLIENT_ID = ""
GOOGLE_CLIENT_SECRET = ""
NEXTAUTH_URL = ""
AUTH_TRUST_HOST = "true"
